### ISSUE TITLE
Soundbug fix

### ISSUE THREAD

**Issue by findcraft** [Tofpu/SpeedBridge2#30]
My Server is on 1.19.3 and I have Via Backwards, Via Rewind and Via Version so I can join on 1.8.9 but if I'm placing any of the blocks, I don't get the place-sound. Is there maybe a way to fix that?

**Comment by Tofpu** [comment]
Sorry for not responding earlier. Does the place-sound issue still occur if the speedbridge plugin is not present in the server?

**Comment by Tofpu** [comment]
Reached out to OP on discord, and they were unable to verify whether this issue is still present. Therefore, I'll be closing this issue down.
